INSERT INTO users (name) VALUES ("mugumogu");
INSERT INTO users (name) VALUES ("Sophie");
INSERT INTO users (name) VALUES ("Penny");
INSERT INTO users (name) VALUES ("John");
INSERT INTO users (name) VALUES ("Bill");
INSERT INTO users (name) VALUES ("Lauren");
INSERT INTO users (name) VALUES ("Christian");
INSERT INTO users (name) VALUES ("Danny");
INSERT INTO users (name) VALUES ("Liam");
INSERT INTO users (name) VALUES ("Skeletor");
INSERT INTO users (name) VALUES ("Quinn");
INSERT INTO users (name) VALUES ("Louis");
INSERT INTO users (name) VALUES ("Marlow");
INSERT INTO users (name) VALUES ("Lama");
INSERT INTO users (name) VALUES ("Bob");
INSERT INTO users (name) VALUES ("Dick");
INSERT INTO users (name) VALUES ("Chad");
INSERT INTO users (name) VALUES ("Mel");
INSERT INTO users (name) VALUES ("Tony");
INSERT INTO users (name) VALUES ("Kimo");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Expansion");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Build");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Funding");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Structure");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("House");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Truck");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bike");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cart");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Apartment");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Condo");